export const string = {
  noSearchResult: "검색 결과가 없어요\n입력하신 검색어가 맞는지 확인해주세요",
  faqNoResult: "아직 FAQ가 없어요",
  brief: "약력",
  record: "이력",
  treatmentSchedule: "진료일정",
  treatmentScheduleGuide: "Schedule",
  treatmentScheduleDescription: "나의미래피부과의 진료시간을 확인해보세요.",
  companyAbout: "About",
  companyAboutDescription: "나의미래피부과를 소개합니다",
  company: "수담의원",
  hospitalIntro: "병원소개",
  medicalStaffIntroduction: "Dermatologist",
  medicalStaffIntroductionDescription:
    "나의미래피부과는 숙련된 의료진과 함께합니다",
  spaceTitle: "수담의 공간",
  doctorOffice: "진료실",
  counselingRoom: "상담실",
  waitingRoom: "대기실",
  medicalStaff: "의료진",
  medicalStaffIntro: "의료진 소개",
  medicalStaffScheduleDescription:
    "의료진별 진료시간이 궁금하신가요? 나의미래피부과의 의료진별 진료시간을 안내해드립니다",
  medicalStaffSchedule: "의료진 진료시간",
  medicalStaffScheduleGuide: "진료시간 안내",
  medicalStaffScheduleDescription2:
    "나의미래피부과 금주의 의료진별 진료시간을 알려드립니다",

  mypage: "마이페이지",
  myInfo: "내 정보",
  guest: "임시회원",
  member: "정회원",
  registration: "등록하기",
  myReservation: "내 예약내역",
  counselingReservation: "상담안내",
  freeCounselingReservation: "무료상담예약",
  reservationComplete: "예약확정",
  reservationReceive: "예약신청",
  reservationCancel: "에약취소",
  reservationEmptyDescription: "최근 예약내역이 없습니다.",
  reservationEmptyDescription2: "예약하러 가볼까요?",
  reservationInfo: "예약 정보",
  reservationDetailInfo: "예약내역 상세",
  reservationDate: "예약정보",
  reservationUserInfo: "예약자 정보",
  reservationReceiveNotification1:
    "병원에서 확인 후 예약이 확정되는 상품이에요.",
  reservationReceiveNotification2:
    "요청하신 일시에 예약 가능한지 확인 후, 카카오톡 알림톡을 통해 알려드릴게요.",
  paymentInfo: "결제정보",
  reservationUserName: "예약자명",
  reservationDetailCaution: "홈페이지를 통해 예약하신 내역만 볼 수 있어요.",
  phoneContact: "연락처",
  makeReservation: "에약하기",
  visitingHospitalInfo: "방문병원 정보",
  visitingScheduleDate: "방문예정 일시",
  parkingWhether: "주차여부",
  request: "요청사항",
  myInfoEdit: "내 정보 수정",
  edit: "수정",
  change: "변경",
  accountManagement: "계정 관리",
  allowingEmail: "이메일 수신 동의",
  allowingSms: "문자 수신 동의",
  allowingTalk: "알림톡 수신 동의",
  phoneCert: "휴대폰 인증하기",
  phoneCertDescription: "휴대폰번호를 변경하기 위해서는\n인증절차가 필요해요.",
  verificationCompletedBtn: "인증완료",
  email: "이메일",
  enterEmail: "이메일 입력",
  save: "저장하기",
  registerMemberDescription:
    "정회원으로 등록하시면 추후 어플을 통해\n내 예약내역과 진료기록을 열람하실 수 있어요.",
  secession: "회원 탈퇴",
  secessionReason: "회원을 탈퇴하시는 이유가 무엇인가요?",
  secessionReasonDetailTitle: "회원 탈퇴 전 아래의 내용을 확인해주세요.",
  secessionReasonDetail1:
    "회원 탈퇴 시 회원 정보 및 서비스 이용 기록은 모두 삭제되며, 삭제된 데이터는 복구가 불가능합니다. 다만 법령에 의하여 보관해야 하는 경우 또는 회사 내부 정책에 의하여 보관해야 하는 정보는 탈퇴 후에도 일정 기간 보관됩니다. 자세한 사항은 개인정보 처리방침에서 확인하실 수 있습니다.",
  secessionReasonDetail2:
    "등록된 리뷰는 자동으로 삭제되지 않으며, 삭제하기를 원하시는 리뷰는 탈퇴 전 반드시 직접 삭제하시기 바랍니다. 탈퇴 후 임의삭제는 불가합니다.",
  secessionReasonDetail3: "회원 탈퇴 후 30일간 재가입이 불가합니다.",
  secessionReasonType1: "사용빈도 낮음",
  secessionReasonType2: "재가입",
  secessionReasonType3: "콘텐츠 / 제품정보 / 상품 부족",
  secessionReasonType4: "개인정보 유출 우려",
  secessionReasonType5: "회원 혜택 부족",
  secessionReasonType6: "기타",
  secessionReasonType7: "직접입력",
  secessionReasonTextareaPlaceholder:
    "회원을 탈퇴하려는 이유를 알려주세요! 더 좋은 서비스로 찾아뵐게요.",
  secessionReasonGuideCheck: "회원 탈퇴에 관한 내용을 모두 확인했어요.",
  secessionReasonBtn: "탈퇴하기",
  secessionReasonSuccess: "회원 탈퇴가 완료되었어요",
  secessionReasonSuccessDescription:
    "그동안 이용해주셔서 감사합니다.\n더 나은 서비스로 찾아뵙겠습니다.",
  membership: "멤버쉽",
  cs: "고객센터",
  membershipDescription: "수담의원 멤버쉽에 가입하고 더 많은 혜택을 누려보세요",
  medicalDepartment: "진료과목",
  faq: "FAQ",
  faqDescription: "자주묻는 질문",
  searchTextPlaceholder: "검색어 입력",
  searchText: "검색어",
  searchBtn: "검색",
  listBackBtn: "목록으로 돌아가기",
  notice: "Notice",
  noticeDescription: "공지사항",
  noticeEmpty: "아직 공지사항이 없어요",
  backRouterBtn: "이전 페이지로",
  subwayLine: "지하철 노선",
  busLine: "버스 노선",
  surgeryViewBtn: "시술 보러가기",
  surgeryAmount: "시술금액",
  discountAmount: "할인금액",
  defaultAmount: "기본할인",
  estimatedAmount: "에상금액",
  taxIncluded: "VAT 별도",
  logout: "로그아웃",
  eventEmpty: "아직 이벤트가 없어요",
};

export const routerLink = {
  mypageReservationDetail: "/mypage/reservation",
  mypageInfoEdit: "/mypage/edit",
  mypageSecession: "/mypage/edit/secession",
  mypageSecessionSuccess: "/mypage/edit/secession/success",
};
